import AdminShell from '@/components/AdminShell';
import {formatManila, readNewsAutopilotState} from '@/lib/newsAutopilot';

export const dynamic = 'force-dynamic';

export default async function NewsAutopilotPage() {
  const state = await readNewsAutopilotState();
  return <AdminShell active="news-autopilot"><div className="admin-title"><p className="eyebrow">NEWS AUTOPILOT</p><h1>新闻自主运营</h1><p>仅管理 News。Blog 不会由本模块自动发布。自动发布默认关闭，所有首批内容先以草稿形式进入审核。</p></div>
    <section className="admin-panel"><h2>运行状态</h2><div className="admin-metrics"><article><span>自动发布</span><strong>{state.enabled ? '已开启' : '已关闭'}</strong><small>默认关闭</small></article><article><span>发布节奏</span><strong>48 小时 / 最多 1 篇</strong><small>Asia/Manila</small></article><article><span>上次发布</span><strong>{state.lastPublishedAt ? formatManila(new Date(state.lastPublishedAt)) : '暂无'}</strong><small>仅记录人工批准后的发布</small></article><article><span>待审核草稿</span><strong>{state.drafts.filter((item) => item.status === 'draft').length}</strong><small>不自动上前台</small></article></div>
      <div className="admin-action-row"><form action="/api/admin/news-autopilot" method="post"><input type="hidden" name="action" value="seed"/><button type="submit">建立首批 6 篇草稿</button></form><form action="/api/admin/news-autopilot" method="post"><input type="hidden" name="action" value="dry-run"/><button type="submit">执行 Dry Run</button></form><form action="/api/admin/news-autopilot" method="post"><input type="hidden" name="action" value="toggle"/><input type="hidden" name="enabled" value={state.enabled ? 'false' : 'true'}/><button type="submit">{state.enabled ? '关闭自动发布' : '开启自动草稿计划'}</button></form></div></section>
    <section className="admin-panel"><h2>来源白名单</h2><div className="admin-table-wrap"><table><thead><tr><th>来源</th><th>地区</th><th>层级</th><th>图片许可</th><th>状态</th></tr></thead><tbody>{state.sources.map((source) => <tr key={source.id}><td><a href={source.url} target="_blank" rel="noreferrer">{source.name}</a><br/><small>{source.domain}</small></td><td>{source.region}</td><td>{source.tier === 'official' ? '官方/监管' : '行业媒体'}</td><td>{source.imageLicense === 'link-card-only' ? '仅来源卡片，不复制图片' : '未提供'}</td><td>{source.enabled ? '启用' : '停用'} / {source.health}</td></tr>)}</tbody></table></div></section>
    <section className="admin-panel"><h2>审核草稿</h2><div className="admin-table-wrap"><table><thead><tr><th>标题</th><th>产品 / 行业</th><th>来源</th><th>校验</th><th>操作</th></tr></thead><tbody>{state.drafts.length ? state.drafts.map((draft) => <tr key={draft.id}><td><strong>{draft.title}</strong><br/><small>{draft.slug}</small></td><td>{draft.productSlugs.join(', ')}<br/><small>{draft.industry} / {draft.structure}</small></td><td><a href={draft.source.url} target="_blank" rel="noreferrer">{draft.source.name}</a></td><td>{draft.validation.length ? draft.validation.join(' ') : '通过'}<br/><small>{draft.status === 'published' ? '已发布' : '待人工审核；非英文版本待编辑'}</small></td><td>{draft.status === 'draft' ? <form action="/api/admin/news-autopilot" method="post"><input type="hidden" name="action" value="publish"/><input type="hidden" name="draftId" value={draft.id}/><button type="submit">批准并发布英文版</button></form> : '已发布'}</td></tr>) : <tr><td colSpan={5}>尚未建立草稿。</td></tr>}</tbody></table></div></section>
    <section className="admin-panel"><h2>最近运行与审计</h2><div className="admin-table-wrap"><table><thead><tr><th>时间</th><th>触发</th><th>状态</th><th>原因</th></tr></thead><tbody>{state.runs.slice().reverse().slice(0, 20).map((run) => <tr key={run.id}><td>{formatManila(new Date(run.finishedAt))}</td><td>{run.trigger}</td><td>{run.status}</td><td>{run.reason}</td></tr>)}</tbody></table></div></section>
  </AdminShell>;
}
